# Generated by Django 5.2.2 on 2025-09-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('gerente', 'Gerente')], default='cliente', max_length=10),
        ),
        migrations.DeleteModel(
            name='Atendente',
        ),
    ]
