# Generated by Django 5.2.2 on 2025-12-04 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0001_initial'),
        ('usuarios', '0002_cliente_limite_credito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_vencimento', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28')], default=10)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_fatura', to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'Configuração de Fatura',
                'verbose_name_plural': 'Configurações de Faturas',
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='aberta', max_length=15)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('juros_mora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-mes_referencia'],
                'unique_together': {('cliente', 'mes_referencia')},
            },
        ),
        migrations.CreateModel(
            name='ItemFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela_numero', models.IntegerField(default=1)),
                ('parcela_total', models.IntegerField(default=1)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=200)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.compra')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='faturas.fatura')),
            ],
            options={
                'verbose_name': 'Item da Fatura',
                'verbose_name_plural': 'Itens da Fatura',
            },
        ),
        migrations.CreateModel(
            name='PagamentoFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('saldo', 'Saldo'), ('pix', 'PIX'), ('transferencia', 'Transferência'), ('boleto', 'Boleto')], max_length=15)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='faturas.fatura')),
            ],
            options={
                'verbose_name': 'Pagamento de Fatura',
                'verbose_name_plural': 'Pagamentos de Faturas',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
