# Generated by Django 5.2.2 on 2025-12-04 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0001_initial'),
        ('usuarios', '0002_cliente_limite_credito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao', models.CharField(choices=[('utilizacao', 'Utilização'), ('pagamento', 'Pagamento'), ('ajuste', 'Ajuste')], max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=200)),
                ('data_operacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_credito', to='usuarios.cliente')),
                ('compra_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.compra')),
            ],
            options={
                'verbose_name': 'Histórico de Crédito',
                'verbose_name_plural': 'Histórico de Crédito',
                'ordering': ['-data_operacao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justificativa', models.TextField()),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('cancelada', 'Cancelada')], default='pendente', max_length=15)),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes_gerente', models.TextField(blank=True)),
                ('valor_aprovado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_credito', to='usuarios.cliente')),
                ('gerente_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_credito', to='usuarios.gerente')),
            ],
            options={
                'verbose_name': 'Solicitação de Crédito',
                'verbose_name_plural': 'Solicitações de Crédito',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
