# Generated by Django 5.2.2 on 2025-12-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocredito',
            name='profissao',
            field=models.CharField(default='Não informado', max_length=100),
        ),
    ]
